name: Generate calendars and indexes
on:
  push:
    branches:
      - main
  schedule:
    - cron: '06,13,20 13 * * *'
  workflow_call:
jobs:
  generate-calendars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Create worktree
        run: |
          git fetch --depth=1 origin calendars:calendars
          git worktree add calendars
      - name: Generate link files
        run: ./pull-calendars "$(pwd)/calendars"
      - name: Save and commit changes
        run: |
          cd calendars
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git branch -u origin/calendars calendars
          (git commit -m "Update calendars" && git push) || true

